[package]
name = "helicase"
version = "0.1.0"
edition = "2024"
authors = ["Igor Martayan <imartayan@users.noreply.github.com>"]
description = "SIMD-accelerated parser for FASTA and FASTQ files"
keywords = ["bioinformatics", "fasta", "fastq", "parser", "simd"]
license = "MIT"

[dependencies]
deko = { version = "0.6", default-features = false }
flate2 = { version = "1.1", features = ["zlib-rs"], optional = true }
memchr = "2.7.6"
memmap2 = "0.9"
paraseq = { version = "0.4", default-features = false, optional = true }
rayon = "1.9"

[features]
default = ["gz", "zstd"]
bz2 = ["deko/bzip2"]
gz = ["deko/flate2", "flate2"]
xz = ["deko/xz"]
zstd = ["deko/zstd"]

[[example]]
name = "paraseq"
required-features = ["paraseq"]
